services:
  - type: worker
    name: telegram-comma-bot
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: ENVIRONMENT
        value: production
      - key: TZ
        value: Europe/Moscow
    autoDeploy: true
